// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef KNOWROBWRAPPERCOMPDEF_KNOWROBWRAPPER_IMPL_H
#define KNOWROBWRAPPERCOMPDEF_KNOWROBWRAPPER_IMPL_H

/************************************************************
 KnowRobWrapper_impl class header
 ************************************************************/

#include "KnowRobWrapperCompdef/Pkg_KnowRobWrapperCompdef.h"

#include "KnowRobWrapperCompdef/KnowRobWrapper.h"
#include "std_msgs/msg/string.hpp"

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}

namespace KnowRobWrapperCompdef {

/************************************************************/
/**
 * This is a skeleton class generated for component KnowRobWrapper
 * Copy it into the source folder as an initial base (or copy parts
 * of it whenever you add modify the component).
 * 
 */
class KnowRobWrapper_impl: public KnowRobWrapper {
public:

	/**
	 * 
	 * @param options 
	 */
	KnowRobWrapper_impl(rclcpp::NodeOptions /*in*/options);

	/**
	 * 
	 * @param string 
	 */
	void ResponseHandler(const std_msgs::msg::String::SharedPtr /*in*/string);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace KnowRobWrapperCompdef

/************************************************************
 End of KnowRobWrapper_impl class header
 ************************************************************/

#endif
