// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define KnowRobWrapperCompdef_KnowRobWrapper_impl_BODY

/************************************************************
 KnowRobWrapper_impl class body
 ************************************************************/

// include associated header file
#include "KnowRobWrapperCompdef/KnowRobWrapper_impl.h"

// Derived includes directives
#include "rclcpp/rclcpp.hpp"

auto msg = std_msgs::msg::String();

namespace KnowRobWrapperCompdef {

// static attributes (if any)

/**
 * 
 * @param options 
 */
KnowRobWrapper_impl::KnowRobWrapper_impl(rclcpp::NodeOptions /*in*/options) :
		KnowRobWrapper(options) {
}

/**
 * 
 * @param string 
 */
void KnowRobWrapper_impl::ResponseHandler(
		const std_msgs::msg::String::SharedPtr /*in*/string) {
			msg = *string;
			//RCLCPP_INFO(this->get_logger(), "KnowRobWrapper has received " + msg);
}

} // of namespace KnowRobWrapperCompdef

/************************************************************
 End of KnowRobWrapper_impl class body
 ************************************************************/
