// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef RGBD_SURFACE_RECONSTRUCTIONCOMPDEF_RGBD_SURFACE_RECONSTRUCTION_H
#define RGBD_SURFACE_RECONSTRUCTIONCOMPDEF_RGBD_SURFACE_RECONSTRUCTION_H

/************************************************************
 Rgbd_surface_reconstruction class header
 ************************************************************/

#include "Rgbd_surface_reconstructionCompdef/Pkg_Rgbd_surface_reconstructionCompdef.h"

#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "sensor_msgs/msg/image.hpp"
#include "shape_msgs/msg/mesh.hpp"

// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>

// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}
namespace ros2Library {
namespace rclcpp {
class Subscription;
}
}

namespace Rgbd_surface_reconstructionCompdef {

/************************************************************/
/**
 * 
 */
class Rgbd_surface_reconstruction: public rclcpp_lifecycle::LifecycleNode {
public:

	/**
	 * 
	 */
	rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr depth_image_sub_;

	/**
	 * 
	 */
	rclcpp_lifecycle::LifecyclePublisher<shape_msgs::msg::Mesh>::SharedPtr surface_mesh_pub_;

	/**
	 * 
	 */
	rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr color_image_sub_;

	/**
	 * 
	 * @param options 
	 */
	Rgbd_surface_reconstruction(rclcpp::NodeOptions /*in*/options);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Rgbd_surface_reconstructionCompdef

/************************************************************
 End of Rgbd_surface_reconstruction class header
 ************************************************************/

#endif
