// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef GARBAGE_CLASSIFICATIONCOMPDEF_GARBAGE_CLASSIFICATION_H
#define GARBAGE_CLASSIFICATIONCOMPDEF_GARBAGE_CLASSIFICATION_H

/************************************************************
 Garbage_classification class header
 ************************************************************/

#include "Garbage_classificationCompdef/Pkg_Garbage_classificationCompdef.h"

#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "sensor_msgs/msg/image.hpp"
#include "std_msgs/msg/string.hpp"

// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>

// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}
namespace ros2Library {
namespace rclcpp {
class Subscription;
}
}

namespace Garbage_classificationCompdef {

/************************************************************/
/**
 * 
 */
class Garbage_classification: public rclcpp_lifecycle::LifecycleNode {
public:

	/**
	 * 
	 */
	rclcpp_lifecycle::LifecyclePublisher<std_msgs::msg::String>::SharedPtr classification_pub_;

	/**
	 * 
	 */
	rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr image_sub_;

	/**
	 * 
	 * @param options 
	 */
	Garbage_classification(rclcpp::NodeOptions /*in*/options);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Garbage_classificationCompdef

/************************************************************
 End of Garbage_classification class header
 ************************************************************/

#endif
