// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Garbage_classificationCompdef_Garbage_classification_impl_BODY

/************************************************************
 Garbage_classification_impl class body
 ************************************************************/

// include associated header file
#include "Garbage_classificationCompdef/Garbage_classification_impl.h"

// Derived includes directives
#include "rclcpp/rclcpp.hpp"

namespace Garbage_classificationCompdef {

// static attributes (if any)

/**
 * 
 * @param options 
 */
Garbage_classification_impl::Garbage_classification_impl(
		rclcpp::NodeOptions /*in*/options) :
		Garbage_classification(options) {
}

/**
 * 
 * @param image 
 */
void Garbage_classification_impl::classify(
		const sensor_msgs::msg::Image::SharedPtr /*in*/image) {
}

} // of namespace Garbage_classificationCompdef

/************************************************************
 End of Garbage_classification_impl class body
 ************************************************************/
