// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define KitchenUtensilClassifierCompdef_KitchenUtensilClassifier_impl_BODY

/************************************************************
 KitchenUtensilClassifier_impl class body
 ************************************************************/

// include associated header file
#include "KitchenUtensilClassifierCompdef/KitchenUtensilClassifier_impl.h"

// Derived includes directives
#include "rclcpp/rclcpp.hpp"

namespace KitchenUtensilClassifierCompdef {

// static attributes (if any)

/**
 * 
 * @param options 
 */
KitchenUtensilClassifier_impl::KitchenUtensilClassifier_impl(
		rclcpp::NodeOptions /*in*/options) :
		KitchenUtensilClassifier(options) {
}

/**
 * 
 * @param image 
 */
void KitchenUtensilClassifier_impl::classifyKitchenUtensil(
		const sensor_msgs::msg::Image::SharedPtr /*in*/image) {
}

} // of namespace KitchenUtensilClassifierCompdef

/************************************************************
 End of KitchenUtensilClassifier_impl class body
 ************************************************************/
