// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define VOSCompdef_VOS_impl_BODY

/************************************************************
 VOS_impl class body
 ************************************************************/

// include associated header file
#include "VOSCompdef/VOS_impl.h"

// Derived includes directives
#include "rclcpp/rclcpp.hpp"

namespace VOSCompdef {

// static attributes (if any)

/**
 * 
 * @param options 
 */
VOS_impl::VOS_impl(rclcpp::NodeOptions /*in*/options) :
		VOS(options) {
}

/**
 * 
 * @param image 
 */
void VOS_impl::fNewFunction(
		const sensor_msgs::msg::Image::SharedPtr /*in*/image) {
}

} // of namespace VOSCompdef

/************************************************************
 End of VOS_impl class body
 ************************************************************/
