// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef VOSCOMPDEF_VOS_IMPL_H
#define VOSCOMPDEF_VOS_IMPL_H

/************************************************************
 VOS_impl class header
 ************************************************************/

#include "sensor_msgs/msg/image.hpp"
#include "../../src/VOSCompdef/Pkg_VOSCompdef.h"
#include "../../src/VOSCompdef/VOS.h"

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}

namespace VOSCompdef {

/************************************************************/
/**
 * This is a skeleton class generated for component VOS
 * Copy it into the source folder as an initial base (or copy parts
 * of it whenever you add modify the component).
 * 
 */
class VOS_impl: public VOS {
public:

	/**
	 * 
	 * @param options 
	 */
	VOS_impl(rclcpp::NodeOptions /*in*/options);

	/**
	 * 
	 * @param image 
	 */
	void fNewFunction(const sensor_msgs::msg::Image::SharedPtr /*in*/image);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace VOSCompdef

/************************************************************
 End of VOS_impl class header
 ************************************************************/

#endif
