// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef RVIZVISUALIZATIONCOMPONENTCOMPDEF_RVIZVISUALIZATIONCOMPONENT_IMPL_H
#define RVIZVISUALIZATIONCOMPONENTCOMPDEF_RVIZVISUALIZATIONCOMPONENT_IMPL_H

/************************************************************
 RVIZVisualizationComponent_impl class header
 ************************************************************/

#include "RVIZVisualizationComponentCompdef/Pkg_RVIZVisualizationComponentCompdef.h"

#include "RVIZVisualizationComponentCompdef/RVIZVisualizationComponent.h"
#include "geometry_msgs/msg/pose_array.hpp"

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}

namespace RVIZVisualizationComponentCompdef {

/************************************************************/
/**
 * This is a skeleton class generated for component RVIZVisualizationComponent
 * Copy it into the source folder as an initial base (or copy parts
 * of it whenever you add modify the component).
 * 
 */
class RVIZVisualizationComponent_impl: public RVIZVisualizationComponent {
public:

	/**
	 * 
	 * @param options 
	 */
	RVIZVisualizationComponent_impl(rclcpp::NodeOptions /*in*/options);

	/**
	 * 
	 * @param posearray 
	 */
	void visualization(
			const geometry_msgs::msg::PoseArray::SharedPtr /*in*/posearray);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace RVIZVisualizationComponentCompdef

/************************************************************
 End of RVIZVisualizationComponent_impl class header
 ************************************************************/

#endif
