// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef TESTCOMPDEF_TEST_H
#define TESTCOMPDEF_TEST_H

/************************************************************
 Test class header
 ************************************************************/

#include "TestCompdef/Pkg_TestCompdef.h"

#include "rclcpp_lifecycle/lifecycle_node.hpp"

// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>
#include "std_msgs/msg/bool.hpp"
// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}

namespace TestCompdef {

/************************************************************/
/**
 * 
 */
class Test: public rclcpp_lifecycle::LifecycleNode {
public:

	/**
	 * 
	 * @param options 
	 */
	  std::shared_ptr<rclcpp_lifecycle::LifecyclePublisher<std_msgs::msg::Bool>> Port_pub;
	Test(rclcpp::NodeOptions /*in*/options);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace TestCompdef

/************************************************************
 End of Test class header
 ************************************************************/

#endif
