// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef KITCHENUTENSILCLASSIFIERCOMPDEF_KITCHENUTENSILCLASSIFIER_H
#define KITCHENUTENSILCLASSIFIERCOMPDEF_KITCHENUTENSILCLASSIFIER_H

/************************************************************
 KitchenUtensilClassifier class header
 ************************************************************/

#include "KitchenUtensilClassifierCompdef/Pkg_KitchenUtensilClassifierCompdef.h"

#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "sensor_msgs/msg/image.hpp"
#include "std_msgs/msg/string.hpp"

// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>

// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}
namespace ros2Library {
namespace rclcpp {
class Subscription;
}
}

namespace KitchenUtensilClassifierCompdef {

/************************************************************/
/**
 * 
 */
class KitchenUtensilClassifier: public rclcpp_lifecycle::LifecycleNode {
public:

	/**
	 * 
	 */
	rclcpp_lifecycle::LifecyclePublisher<std_msgs::msg::String>::SharedPtr utensilClass_pub_;

	/**
	 * 
	 */
	rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr image_sub_;

	/**
	 * 
	 * @param options 
	 */
	KitchenUtensilClassifier(rclcpp::NodeOptions /*in*/options);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace KitchenUtensilClassifierCompdef

/************************************************************
 End of KitchenUtensilClassifier class header
 ************************************************************/

#endif
