// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CAMERADRIVERCOMPONENTCOMPDEF_CAMERADRIVERCOMPONENT_IMPL_H
#define CAMERADRIVERCOMPONENTCOMPDEF_CAMERADRIVERCOMPONENT_IMPL_H

/************************************************************
 CameraDriverComponent_impl class header
 ************************************************************/

#include "CameraDriverComponentCompdef/Pkg_CameraDriverComponentCompdef.h"

#include "CameraDriverComponentCompdef/CameraDriverComponent.h"
#include "sensor_msgs/msg/image.hpp"

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}

namespace CameraDriverComponentCompdef {

/************************************************************/
/**
 * This is a skeleton class generated for component CameraDriverComponent
 * Copy it into the source folder as an initial base (or copy parts
 * of it whenever you add modify the component).
 * 
 */
class CameraDriverComponent_impl: public CameraDriverComponent {
public:

	/**
	 * 
	 * @param options 
	 */
	CameraDriverComponent_impl(rclcpp::NodeOptions /*in*/options);

	/**
	 * 
	 * @param image 
	 */
	void publishVideo(const sensor_msgs::msg::Image::SharedPtr /*in*/image);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace CameraDriverComponentCompdef

/************************************************************
 End of CameraDriverComponent_impl class header
 ************************************************************/

#endif
