// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef FRUIT_DETECTIONCOMPDEF_FRUITDETECTION_H
#define FRUIT_DETECTIONCOMPDEF_FRUITDETECTION_H

/************************************************************
 FruitDetection class header
 ************************************************************/

#include "Fruit_detectionCompdef/Pkg_Fruit_detectionCompdef.h"

#include "fruit_detection/msg/boxes_image.hpp"
#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "sensor_msgs/msg/image.hpp"
#include "std_msgs/msg/string.hpp"

// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>

// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}
namespace ros2Library {
namespace rclcpp {
class Subscription;
}
}

namespace Fruit_detectionCompdef {

/************************************************************/
/**
 * 
 */
class FruitDetection: public rclcpp_lifecycle::LifecycleNode {
public:

	/**
	 * 
	 */
	rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr image_sub_;

	/**
	 * 
	 */
	rclcpp_lifecycle::LifecyclePublisher<fruit_detection::msg::BoxesImage>::SharedPtr BoxImage_pub_;

	/**
	 * 
	 * @param options 
	 */
	FruitDetection(rclcpp::NodeOptions /*in*/options);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Fruit_detectionCompdef

/************************************************************
 End of FruitDetection class header
 ************************************************************/

#endif
