// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef VOSCOMPDEF_VOS_H
#define VOSCOMPDEF_VOS_H

/************************************************************
 VOS class header
 ************************************************************/

#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "sensor_msgs/msg/image.hpp"


#include <torch/script.h>


#include "opencv2/core/core.hpp"
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/objdetect.hpp"
#include "opencv2/opencv.hpp"
#include "../../src/VOSCompdef/Pkg_VOSCompdef.h"
#include <cv_bridge/cv_bridge.h>

using namespace cv;


// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>
#include <iostream>
#include <string>

// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}
namespace ros2Library {
namespace rclcpp {
class Subscription;
}
}

namespace VOSCompdef {

/************************************************************/
/**
 * 
 */
class VOS: public rclcpp_lifecycle::LifecycleNode {
public:

	/**
	 * 
	 */
	rclcpp_lifecycle::LifecyclePublisher<sensor_msgs::msg::Image>::SharedPtr segmentation_pub_;

	/**
	 * 
	 */
	rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr image_sub_;

	/**
	 * 
	 * @param options 
	 */

	void fNewFunction(const sensor_msgs::msg::Image::SharedPtr /*in*/image);

	VOS(rclcpp::NodeOptions /*in*/options);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace VOSCompdef

/************************************************************
 End of VOS class header
 ************************************************************/

#endif
