// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef KITCHENUTENSILCLASSIFIERCOMPDEF_KITCHENUTENSILCLASSIFIER_IMPL_H
#define KITCHENUTENSILCLASSIFIERCOMPDEF_KITCHENUTENSILCLASSIFIER_IMPL_H

/************************************************************
 KitchenUtensilClassifier_impl class header
 ************************************************************/

#include "KitchenUtensilClassifierCompdef/Pkg_KitchenUtensilClassifierCompdef.h"

#include "KitchenUtensilClassifierCompdef/KitchenUtensilClassifier.h"
#include "sensor_msgs/msg/image.hpp"

#include <opencv2/core.hpp>
#include <opencv2/dnn.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}

namespace KitchenUtensilClassifierCompdef {

/************************************************************/
/**
 * This is a skeleton class generated for component KitchenUtensilClassifier
 * Copy it into the source folder as an initial base (or copy parts
 * of it whenever you add modify the component).
 * 
 */
class KitchenUtensilClassifier_impl: public KitchenUtensilClassifier {
public:

	/**
	 * 
	 * @param options 
	 */
	KitchenUtensilClassifier_impl(rclcpp::NodeOptions /*in*/options);

	/**
	 * 
	 * @param image 
	 */
	void classifyKitchenUtensil(
			const sensor_msgs::msg::Image::SharedPtr /*in*/image);

private:
	static const int inputWidth = 224;
	static const int inputHeight = 224;
	cv::dnn::Net net;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace KitchenUtensilClassifierCompdef

/************************************************************
 End of KitchenUtensilClassifier_impl class header
 ************************************************************/

#endif
