// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef KITCHENUTENSILCLASSIFIERCOMPDEF_KITCHENUTENSILCLASSIFIER_IMPL_H
#define KITCHENUTENSILCLASSIFIERCOMPDEF_KITCHENUTENSILCLASSIFIER_IMPL_H

/************************************************************
 KitchenUtensilClassifier_impl class header
 ************************************************************/

#include "KitchenUtensilClassifierCompdef/Pkg_KitchenUtensilClassifierCompdef.h"

#include "KitchenUtensilClassifierCompdef/KitchenUtensilClassifier.h"
#include "sensor_msgs/msg/image.hpp"

#include <opencv2/core.hpp>
#include <opencv2/dnn.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}

namespace KitchenUtensilClassifierCompdef {

/************************************************************/
/**
 * This is a skeleton class generated for component KitchenUtensilClassifier
 * Copy it into the source folder as an initial base (or copy parts
 * of it whenever you add modify the component).
 * 
 */
class KitchenUtensilClassifier_impl: public KitchenUtensilClassifier {
public:

	/**
	 * 
	 * @param options 
	 */
	KitchenUtensilClassifier_impl(rclcpp::NodeOptions /*in*/options);

	/**
	 * 
	 * @param image 
	 */
	void classifyKitchenUtensil(
			const sensor_msgs::msg::Image::SharedPtr /*in*/image);

private:
	void read_classes_from_file(const char *path);
	void debug_confidences(cv::Mat *confidences);
	void debug_net_efficiency();

	cv::dnn::Net net;
	int counter;
	std::vector<const char*> classes;
	cv::Scalar mean = cv::Scalar(124.16, 116.736, 103.936);

	/*
	 * These are statically chosen values that depend on the model being used;
	 * VGG19 for example uses an input width and height of 224 pixels
	 */
	static const int inputWidth = 224;
	static const int inputHeight = 224;

	/*
	 * This is an empirically found value, and could potentially be replaced
	 * in the future
	 */

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace KitchenUtensilClassifierCompdef

/************************************************************
 End of KitchenUtensilClassifier_impl class header
 ************************************************************/

#endif
