// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define KitchenUtensilClassifierCompdef_KitchenUtensilClassifier_impl_BODY

#define MODEL_PATH "data/kitchen_classifier.onnx"

/************************************************************
 KitchenUtensilClassifier_impl class body
 ************************************************************/

// include associated header file
#include "KitchenUtensilClassifierCompdef/KitchenUtensilClassifier_impl.h"

// Derived includes directives
#include "rclcpp/rclcpp.hpp"
#include "stdio.h"

#include <unistd.h>

using namespace cv;

namespace KitchenUtensilClassifierCompdef {

// static attributes (if any)

/**
 * 
 * @param options 
 */
KitchenUtensilClassifier_impl::KitchenUtensilClassifier_impl(
		rclcpp::NodeOptions /*in*/options) :
		KitchenUtensilClassifier(options) {
	net = dnn::readNet(MODEL_PATH);
}

/**
 * 
 * @param image 
 */
void KitchenUtensilClassifier_impl::classifyKitchenUtensil(
		const sensor_msgs::msg::Image::SharedPtr /*in*/image) {
	Mat blob;
	Mat frame(image->height, image->width, CV_8UC3, image->data.data());

    Scalar mean = 100;
    double scaleFactor = 1.0;
    Size inputSize(inputWidth, inputHeight);

    blob = dnn::blobFromImage(frame, scaleFactor, inputSize, mean);
    net.setInput(blob);
    Mat prob = net.forward();
    Point classIdPoint;
    double confidence;
    minMaxLoc(prob.reshape(1, 1), 0, &confidence, 0, &classIdPoint);
    int classId = classIdPoint.x;

    // Output efficiency information.
    std::vector<double> layersTimes;
    double freq = getTickFrequency() / 1000;
    double t = net.getPerfProfile(layersTimes) / freq;
    // Print predicted class.
    RCLCPP_INFO(this->get_logger(), format("Inference time: %.2f ms", t));
    RCLCPP_INFO(this->get_logger(),
    			format("%s: %.4f", (format("Class #%d",classId).c_str()), confidence));
}


} // of namespace KitchenUtensilClassifierCompdef

/************************************************************
 End of KitchenUtensilClassifier_impl class body
 ************************************************************/
