// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define SurfaceReconstructionCompdef_SurfaceReconstruction_impl_BODY

/************************************************************
 SurfaceReconstruction_impl class body
 ************************************************************/

// include associated header file
#include "SurfaceReconstructionCompdef/SurfaceReconstruction_impl.h"

// Derived includes directives
#include "rclcpp/rclcpp.hpp"

namespace SurfaceReconstructionCompdef {

// static attributes (if any)

/**
 * 
 * @param options 
 */
SurfaceReconstruction_impl::SurfaceReconstruction_impl(
		rclcpp::NodeOptions /*in*/options) :
		SurfaceReconstruction(options) {
}

/**
 * 
 * @param image 
 */
void SurfaceReconstruction_impl::surface_mesh_handler(
		const sensor_msgs::msg::Image::SharedPtr /*in*/image) {
}

} // of namespace SurfaceReconstructionCompdef

/************************************************************
 End of SurfaceReconstruction_impl class body
 ************************************************************/
