// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SURFACERECONSTRUCTIONCOMPDEF_FNEWFUNCTION_H
#define SURFACERECONSTRUCTIONCOMPDEF_FNEWFUNCTION_H

/************************************************************
 fNewFunction class header
 ************************************************************/

#include "SurfaceReconstructionCompdef/Pkg_SurfaceReconstructionCompdef.h"

namespace SurfaceReconstructionCompdef {

/************************************************************/
/**
 * 
 */
class fNewFunction {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace SurfaceReconstructionCompdef

/************************************************************
 End of fNewFunction class header
 ************************************************************/

#endif
