// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define SurfaceReconstructionCompdef_fNewFunction_BODY

/************************************************************
 fNewFunction class body
 ************************************************************/

// include associated header file
#include "SurfaceReconstructionCompdef/fNewFunction.h"

// Derived includes directives

namespace SurfaceReconstructionCompdef {

// static attributes (if any)

}// of namespace SurfaceReconstructionCompdef

/************************************************************
 End of fNewFunction class body
 ************************************************************/
