// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SURFACERECONSTRUCTIONCOMPDEF_SURFACERECONSTRUCTION_H
#define SURFACERECONSTRUCTIONCOMPDEF_SURFACERECONSTRUCTION_H

/************************************************************
 SurfaceReconstruction class header
 ************************************************************/

#include "SurfaceReconstructionCompdef/Pkg_SurfaceReconstructionCompdef.h"

#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "sensor_msgs/msg/image.hpp"
#include "shape_msgs/msg/mesh.hpp"

// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>

// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}
namespace ros2Library {
namespace rclcpp {
class Subscription;
}
}

namespace SurfaceReconstructionCompdef {

/************************************************************/
/**
 * 
 */
class SurfaceReconstruction: public rclcpp_lifecycle::LifecycleNode {
public:

	/**
	 * 
	 */
	rclcpp_lifecycle::LifecyclePublisher<shape_msgs::msg::Mesh>::SharedPtr surface_mesh_pub_;

	/**
	 * 
	 */
	rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr depth_image_sub_;

	/**
	 * 
	 * @param options 
	 */
	SurfaceReconstruction(rclcpp::NodeOptions /*in*/options);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace SurfaceReconstructionCompdef

/************************************************************
 End of SurfaceReconstruction class header
 ************************************************************/

#endif
