// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define SurfaceReconstructionCompdef_SurfaceReconstruction_BODY

/************************************************************
 SurfaceReconstruction class body
 ************************************************************/

// include associated header file
#include "SurfaceReconstructionCompdef/SurfaceReconstruction.h"

// Derived includes directives
#include "SurfaceReconstructionCompdef/SurfaceReconstruction_impl.h"
#include "rclcpp/rclcpp.hpp"

// Include from Include declaration (body)
// declare options
rclcpp::NodeOptions surfacereconstruction_options;

int main(int argc, char **argv) {
	rclcpp::init(argc, argv);

	auto surfacereconstruction = std::make_shared<
			SurfaceReconstructionCompdef::SurfaceReconstruction_impl>(
			surfacereconstruction_options);

	RCLCPP_INFO(surfacereconstruction->get_logger(),
			"SurfaceReconstruction has been initialized");

	rclcpp::executors::MultiThreadedExecutor executor;

	executor.add_node(surfacereconstruction->get_node_base_interface());

	executor.spin();
	rclcpp::shutdown();
}

// End of Include declaration (body)

namespace SurfaceReconstructionCompdef {

// static attributes (if any)

/**
 * 
 * @param options 
 */
SurfaceReconstruction::SurfaceReconstruction(rclcpp::NodeOptions /*in*/options) :
		rclcpp_lifecycle::LifecycleNode("SurfaceReconstruction", options) {
	surface_mesh_pub_ = create_publisher<shape_msgs::msg::Mesh>("surface_mesh",
			1);
	// directly activate a publisher
	surface_mesh_pub_->on_activate();

	depth_image_sub_ =
			create_subscription<sensor_msgs::msg::Image>("depth_image",
					rclcpp::QoS(rclcpp::KeepLast(100)).best_effort(),
					std::bind(
							&SurfaceReconstructionCompdef::SurfaceReconstruction_impl::surface_mesh_handler,
							(SurfaceReconstruction_impl*) this,
							std::placeholders::_1));

}

} // of namespace SurfaceReconstructionCompdef

/************************************************************
 End of SurfaceReconstruction class body
 ************************************************************/
