// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef VOSCOMPDEF_VOS_H
#define VOSCOMPDEF_VOS_H

/************************************************************
 VOS class header
 ************************************************************/

#include "VOSCompdef/Pkg_VOSCompdef.h"

#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "sensor_msgs/msg/image.hpp"

// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>

// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}
namespace ros2Library {
namespace rclcpp {
class Subscription;
}
}

namespace VOSCompdef {

/************************************************************/
/**
 * 
 */
class VOS: public rclcpp_lifecycle::LifecycleNode {
public:

	/**
	 * 
	 */
	rclcpp_lifecycle::LifecyclePublisher<sensor_msgs::msg::Image>::SharedPtr segmentation_pub_;

	/**
	 * 
	 */
	rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr image_sub_;

	/**
	 * 
	 * @param options 
	 */

	void fNewFunction(const sensor_msgs::msg::Image::SharedPtr /*in*/image);

	VOS(rclcpp::NodeOptions /*in*/options);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace VOSCompdef

/************************************************************
 End of VOS class header
 ************************************************************/

#endif
