// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef FACE_RECOGNITIONCOMPDEF_NEW FUNCTION_H
#define FACE_RECOGNITIONCOMPDEF_NEW FUNCTION_H

/************************************************************
 New Function class header
 ************************************************************/

#include "Face_recognitionCompdef/Pkg_Face_recognitionCompdef.h"

namespace Face_recognitionCompdef {

/************************************************************/
/**
 * 
 */
class New Function {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Face_recognitionCompdef

/************************************************************
 End of New Function class header
 ************************************************************/

#endif
