// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Face_recognitionCompdef_New Function_BODY

/************************************************************
 New Function class body
 ************************************************************/

// include associated header file
#include "Face_recognitionCompdef/New Function.h"

// Derived includes directives

namespace Face_recognitionCompdef {

// static attributes (if any)

}// of namespace Face_recognitionCompdef

/************************************************************
 End of New Function class body
 ************************************************************/
