// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CAMERADRIVERCOMPONENTCOMPDEF_CAMERADRIVERCOMPONENT_H
#define CAMERADRIVERCOMPONENTCOMPDEF_CAMERADRIVERCOMPONENT_H

/************************************************************
 CameraDriverComponent class header
 ************************************************************/

#include "CameraDriverComponentCompdef/Pkg_CameraDriverComponentCompdef.h"

#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "sensor_msgs/msg/image.hpp"

// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>

// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}
namespace ros2Library {
namespace rclcpp {
class Subscription;
}
}

namespace CameraDriverComponentCompdef {

/************************************************************/
/**
 * 
 */
class CameraDriverComponent: public rclcpp_lifecycle::LifecycleNode {
public:

	/**
	 * 
	 */
	rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr video_output_recv_;

	/**
	 * 
	 * @param options 
	 */
	CameraDriverComponent(rclcpp::NodeOptions /*in*/options);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace CameraDriverComponentCompdef

/************************************************************
 End of CameraDriverComponent class header
 ************************************************************/

#endif
