// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef KNOWROBWRAPPERCOMPDEF_KNOWROBWRAPPER_H
#define KNOWROBWRAPPERCOMPDEF_KNOWROBWRAPPER_H

/************************************************************
 KnowRobWrapper class header
 ************************************************************/

#include "KnowRobWrapperCompdef/Pkg_KnowRobWrapperCompdef.h"

#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "std_msgs/msg/string.hpp"

// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>

// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}
namespace ros2Library {
namespace rclcpp {
class Subscription;
}
}

namespace KnowRobWrapperCompdef {

/************************************************************/
/**
 * 
 */
class KnowRobWrapper: public rclcpp_lifecycle::LifecycleNode {
public:

	/**
	 * 
	 */
	rclcpp_lifecycle::LifecyclePublisher<std_msgs::msg::String>::SharedPtr query_pub_;

	/**
	 * 
	 */
	rclcpp::Subscription<std_msgs::msg::String>::SharedPtr response_sub_;
	
	/**
	 * 
	 * @param string 
	 */
	void ResponseHandler(const std_msgs::msg::String::SharedPtr /*in*/string);

	/**
	 * 
	 * @param options 
	 */
	KnowRobWrapper(rclcpp::NodeOptions /*in*/options);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace KnowRobWrapperCompdef

/************************************************************
 End of KnowRobWrapper class header
 ************************************************************/

#endif
