// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SURFACERECONSTRUCTIONCOMPDEF_SURFACERECONSTRUCTION_IMPL_H
#define SURFACERECONSTRUCTIONCOMPDEF_SURFACERECONSTRUCTION_IMPL_H

/************************************************************
 SurfaceReconstruction_impl class header
 ************************************************************/

#include "SurfaceReconstructionCompdef/Pkg_SurfaceReconstructionCompdef.h"

#include "SurfaceReconstructionCompdef/SurfaceReconstruction.h"
#include "sensor_msgs/msg/image.hpp"

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}

namespace SurfaceReconstructionCompdef {

/************************************************************/
/**
 * This is a skeleton class generated for component SurfaceReconstruction
 * Copy it into the source folder as an initial base (or copy parts
 * of it whenever you add modify the component).
 * 
 */
class SurfaceReconstruction_impl: public SurfaceReconstruction {
public:

	/**
	 * 
	 * @param options 
	 */
	SurfaceReconstruction_impl(rclcpp::NodeOptions /*in*/options);

	/**
	 * 
	 * @param image 
	 */
	void surface_mesh_handler(
			const sensor_msgs::msg::Image::SharedPtr /*in*/image);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace SurfaceReconstructionCompdef

/************************************************************
 End of SurfaceReconstruction_impl class header
 ************************************************************/

#endif
